In [13]:
import pandas as pd
df = pd.read_excel('score.xlsx',index_col='지원번호')

## 데이터 추가
df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
df['평균'] = df['합계']/5
df['결과'] = 'Fail'

컬럼 순서변경

In [10]:
cols = list(df.columns)
cols

['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기', '합계', '평균', '결과']

컬럼이름 변경

In [17]:
# 컬럼이름 전체변경
df.columns = ['name','school','height','kor','eng','math','science','society','sw']

# 컬럼이름 변경
df.rename(columns={'이름':'name','학교':'school'})
df
df.rename(index={'1번':'no1'})

ValueError: Length mismatch: Expected axis has 12 elements, new values have 9 elements

In [ ]:
# cols[1:-1]  # 여러개 - list타입
# cols[-1]  # 1개 - 문자열
cols = list(df.columns)
# df[df.columns]

# df [이름,평균,학교:결과] - df[] 리스트타입만 가능
df = df[[cols[0]]+[cols[-1]]+cols[1:-1]]
df

       이름    결과    학교    키   국어   영어   수학  과학  사회        SW특기   합계    평균
지원번호
1번    강나래  Fail   구로고  197   90   85  100  95  85      Python  455  91.0
2번    강태원  Fail   구로고  184   40   35   50  55  25        Java  205  41.0
3번    강호림  Fail   구로고  168   80   75   70  80  75  Javascript  380  76.0
4번    김수찬  Fail   구로고  187   40   60   70  75  80         NaN  325  65.0
5번    김재욱  Fail   구로고  188   15   20   10  35  10         NaN   90  18.0
6번    박동현  Fail  디지털고  202   80  100   95  85  80           C  440  88.0
7번    박혜정  Fail  디지털고  188   55   65   45  40  35      PYTHON  240  48.0
8번    승근열  Fail  디지털고  190  100   85   90  95  95          C#  465  93.0